import type { CatalogueItemRow, ServiceCategoryRow } from "./types";

// Typed fallback used when Supabase isn't configured. Mirrors
// db/migrations/20260609_1040_seed_catalogue.sql so dev and live data match.

export const SEED_CATEGORIES: ServiceCategoryRow[] = [
  {
    id: "seed-cat-activities",
    slug: "activities",
    name_en: "Activities",
    name_ar: "الأنشطة",
    tagline_en: "Competitions, trips, and events",
    tagline_ar: "مسابقات ورحلات وفعاليات",
    description_en:
      "Competitions, indoor and outdoor trips, and school events your students will remember.",
    description_ar: "مسابقات، ورحلات داخلية وخارجية، وفعاليات مدرسية يتذكّرها طلابك.",
    sort_order: 1,
    is_active: true,
  },
  {
    id: "seed-cat-school-services",
    slug: "school-services",
    name_en: "School Services",
    name_ar: "الخدمات المدرسية",
    tagline_en: "Uniforms, gifts, and merchandise",
    tagline_ar: "أزياء وهدايا ومنتجات",
    description_en: "Uniforms, teacher-day gifts, and event merchandise — sourced, branded, and delivered.",
    description_ar: "أزياء مدرسية، وهدايا يوم المعلّم، ومنتجات الفعاليات — توريد وتجهيز وتوصيل.",
    sort_order: 2,
    is_active: true,
  },
  {
    id: "seed-cat-graduation",
    slug: "graduation",
    name_en: "Graduation",
    name_ar: "التخرّج",
    tagline_en: "Gowns, ceremonies, and coordination",
    tagline_ar: "أثواب وحفلات وتنسيق",
    description_en:
      "Gowns, ceremony packages, and full coordination for a graduation day that runs itself.",
    description_ar: "أثواب وباقات حفلات وتنسيق كامل ليوم تخرّج يُدار بسلاسة.",
    sort_order: 3,
    is_active: true,
  },
];

function item(
  partial: Omit<CatalogueItemRow, "image_url" | "is_active"> & Partial<Pick<CatalogueItemRow, "image_url" | "is_active">>,
): CatalogueItemRow {
  return { image_url: null, is_active: true, ...partial };
}

export const SEED_ITEMS: CatalogueItemRow[] = [
  item({
    id: "seed-activities-science-fair",
    category_id: "seed-cat-activities",
    category_slug: "activities",
    slug: "science-fair",
    name_en: "Science Fair Package",
    name_ar: "باقة معرض العلوم",
    summary_en: "An end-to-end science competition for your school.",
    summary_ar: "مسابقة علمية متكاملة لمدرستك.",
    description_en:
      "We plan, judge, and run your science fair from the first call to the awards — booths, scoring, medals, and certificates all included.",
    description_ar:
      "نخطّط ونحكّم وننفّذ معرض العلوم من أول اتصال حتى توزيع الجوائز — تشمل الأجنحة والتقييم والميداليات والشهادات.",
    features_en: ["Full event planning", "Judging and scoring", "Medals and certificates"],
    features_ar: ["تخطيط كامل للفعالية", "تحكيم وتقييم", "ميداليات وشهادات"],
    price_label_en: "Request a quote",
    price_label_ar: "اطلب عرض سعر",
    is_featured: true,
    sort_order: 1,
  }),
  item({
    id: "seed-activities-museum-day",
    category_id: "seed-cat-activities",
    category_slug: "activities",
    slug: "museum-day",
    name_en: "Museum & Discovery Day",
    name_ar: "يوم المتحف والاكتشاف",
    summary_en: "A guided indoor trip that turns a lesson into an adventure.",
    summary_ar: "رحلة داخلية موجّهة تحوّل الدرس إلى مغامرة.",
    description_en:
      "Transport, tickets, guides, and a safety plan for an indoor day of discovery, sized to your class.",
    description_ar: "النقل والتذاكر والمرشدون وخطة السلامة ليوم داخلي من الاكتشاف، مُصمّم لحجم صفّك.",
    features_en: ["Transport and tickets", "Trained guides", "Full safety plan"],
    features_ar: ["النقل والتذاكر", "مرشدون مدرّبون", "خطة سلامة كاملة"],
    price_label_en: "Request a quote",
    price_label_ar: "اطلب عرض سعر",
    is_featured: false,
    sort_order: 2,
  }),
  item({
    id: "seed-activities-adventure-camp",
    category_id: "seed-cat-activities",
    category_slug: "activities",
    slug: "adventure-camp",
    name_en: "Outdoor Adventure Camp",
    name_ar: "مخيّم المغامرات الخارجي",
    summary_en: "A day outdoors with games, teamwork, and supervision.",
    summary_ar: "يوم في الهواء الطلق مع الألعاب والعمل الجماعي والإشراف.",
    description_en:
      "Outdoor activities, meals, equipment, and trained supervisors for a safe day that builds teamwork.",
    description_ar: "أنشطة خارجية ووجبات ومعدّات ومشرفون مدرّبون ليوم آمن يبني روح الفريق.",
    features_en: ["Activities and equipment", "Meals included", "Trained supervisors"],
    features_ar: ["أنشطة ومعدّات", "وجبات مشمولة", "مشرفون مدرّبون"],
    price_label_en: "Request a quote",
    price_label_ar: "اطلب عرض سعر",
    is_featured: false,
    sort_order: 3,
  }),
  item({
    id: "seed-school-services-uniform-program",
    category_id: "seed-cat-school-services",
    category_slug: "school-services",
    slug: "uniform-program",
    name_en: "School Uniform Program",
    name_ar: "برنامج الزي المدرسي",
    summary_en: "Quality uniforms, sized, branded, and delivered to your school.",
    summary_ar: "أزياء عالية الجودة، بمقاسات وعلامة مدرستك، تُوصَّل إليك.",
    description_en:
      "From measuring to delivery: durable uniforms with your school crest, in every size, restocked when you need.",
    description_ar: "من القياس إلى التوصيل: أزياء متينة بشعار مدرستك، بكل المقاسات، مع إعادة التزويد عند الحاجة.",
    features_en: ["On-site sizing", "School crest branding", "Easy restocking"],
    features_ar: ["قياس في الموقع", "طباعة شعار المدرسة", "إعادة تزويد سهلة"],
    price_label_en: "Request a quote",
    price_label_ar: "اطلب عرض سعر",
    is_featured: true,
    sort_order: 1,
  }),
  item({
    id: "seed-school-services-teacher-gifts",
    category_id: "seed-cat-school-services",
    category_slug: "school-services",
    slug: "teacher-gifts",
    name_en: "Teacher Appreciation Gifts",
    name_ar: "هدايا تكريم المعلّمين",
    summary_en: "Thoughtful, branded gifts for Teacher Day.",
    summary_ar: "هدايا مدروسة تحمل علامتكم ليوم المعلّم.",
    description_en:
      "Curated gift sets, personalised with your school name, packaged and ready to hand out.",
    description_ar: "مجموعات هدايا منتقاة، مخصّصة باسم مدرستك، مغلّفة وجاهزة للتوزيع.",
    features_en: ["Curated gift sets", "Personalised packaging", "Bulk delivery"],
    features_ar: ["مجموعات هدايا منتقاة", "تغليف مخصّص", "توصيل بالجملة"],
    price_label_en: "Request a quote",
    price_label_ar: "اطلب عرض سعر",
    is_featured: false,
    sort_order: 2,
  }),
  item({
    id: "seed-school-services-event-merch",
    category_id: "seed-cat-school-services",
    category_slug: "school-services",
    slug: "event-merch",
    name_en: "Event Merchandise Pack",
    name_ar: "حزمة منتجات الفعاليات",
    summary_en: "T-shirts, caps, and banners for your big day.",
    summary_ar: "قمصان وقبّعات ولافتات ليومك الكبير.",
    description_en:
      "Branded merchandise for sports days, festivals, and competitions — designed, produced, and delivered on time.",
    description_ar: "منتجات تحمل علامتكم لأيام الرياضة والمهرجانات والمسابقات — تصميم وإنتاج وتوصيل في الموعد.",
    features_en: ["Custom designs", "T-shirts and caps", "Banners and signage"],
    features_ar: ["تصاميم مخصّصة", "قمصان وقبّعات", "لافتات ولوحات"],
    price_label_en: "Request a quote",
    price_label_ar: "اطلب عرض سعر",
    is_featured: false,
    sort_order: 3,
  }),
  item({
    id: "seed-graduation-grad-gowns",
    category_id: "seed-cat-graduation",
    category_slug: "graduation",
    slug: "grad-gowns",
    name_en: "Graduation Gowns & Caps",
    name_ar: "أثواب وقبّعات التخرّج",
    summary_en: "Comfortable gowns and caps in your school colours.",
    summary_ar: "أثواب وقبّعات مريحة بألوان مدرستك.",
    description_en:
      "Sized for every graduate, in your school colours, with optional sashes and tassels — rented or owned.",
    description_ar: "بمقاسات لكل خرّيج، بألوان مدرستك، مع أوشحة وشراشيب اختيارية — للإيجار أو التملّك.",
    features_en: ["Every size", "School colours", "Sashes and tassels"],
    features_ar: ["كل المقاسات", "ألوان المدرسة", "أوشحة وشراشيب"],
    price_label_en: "Request a quote",
    price_label_ar: "اطلب عرض سعر",
    is_featured: true,
    sort_order: 1,
  }),
  item({
    id: "seed-graduation-ceremony-package",
    category_id: "seed-cat-graduation",
    category_slug: "graduation",
    slug: "ceremony-package",
    name_en: "Ceremony Package",
    name_ar: "باقة الحفل",
    summary_en: "Stage, sound, and décor for a memorable ceremony.",
    summary_ar: "مسرح وصوت وديكور لحفل لا يُنسى.",
    description_en:
      "Stage, sound, lighting, seating, and décor — set up and run so your team can enjoy the day.",
    description_ar: "مسرح وصوت وإضاءة ومقاعد وديكور — تجهيز وتشغيل ليستمتع فريقك باليوم.",
    features_en: ["Stage and sound", "Décor and seating", "On-site team"],
    features_ar: ["مسرح وصوت", "ديكور ومقاعد", "فريق في الموقع"],
    price_label_en: "Request a quote",
    price_label_ar: "اطلب عرض سعر",
    is_featured: false,
    sort_order: 2,
  }),
  item({
    id: "seed-graduation-grad-coordination",
    category_id: "seed-cat-graduation",
    category_slug: "graduation",
    slug: "grad-coordination",
    name_en: "Graduation Coordination",
    name_ar: "تنسيق التخرّج",
    summary_en: "One coordinator to run the whole graduation day.",
    summary_ar: "منسّق واحد لإدارة يوم التخرّج بالكامل.",
    description_en:
      "A dedicated coordinator handles the schedule, rehearsals, vendors, and the run of show from start to finish.",
    description_ar: "منسّق مخصّص يدير الجدول والبروفات والموردين وسير الحفل من البداية إلى النهاية.",
    features_en: ["Dedicated coordinator", "Rehearsals and run of show", "Vendor management"],
    features_ar: ["منسّق مخصّص", "بروفات وإدارة الحفل", "إدارة الموردين"],
    price_label_en: "Request a quote",
    price_label_ar: "اطلب عرض سعر",
    is_featured: false,
    sort_order: 3,
  }),
];
